mqtt:
  host: mqtt
  port: 1883
  user:
  pass:

receiver:
  receiver1:
    x: 2
    y: 2
  receiver2:
    x: 15
    y: 2
  receiver3:
    x: 15
    y: 17
  receiver4:
    x: 2
    y: 17

strangerdetection:
  mindistance: 5
  maxdistance: 40

ledColor:
  yellow: 5
  orange: 10
  red: 15
  # green before the number in yellow

areaColor:
  yellow: 5
  orange: 10
  red: 15
  # green before the number in yellow

areas:
  - name: Frischebereich
    points:
      - [0, 0]
      - [0, 10]
      - [10, 10]
      - [10, 0 ]